[package]
name = "usd-test"
version = "0.1.0"
authors = ["Luke Titley <luke@titley.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
usd = {path="../usd-rs"}
